/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WisataRouteImport } from './routes/wisata'
import { Route as TeknologiRouteImport } from './routes/teknologi'
import { Route as SejarahRouteImport } from './routes/sejarah'
import { Route as PetaRouteImport } from './routes/peta'
import { Route as KulinerRouteImport } from './routes/kuliner'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as BudayaRouteImport } from './routes/budaya'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WisataSlugRouteImport } from './routes/wisata.$slug'

const WisataRoute = WisataRouteImport.update({
  id: '/wisata',
  path: '/wisata',
  getParentRoute: () => rootRouteImport,
} as any)
const TeknologiRoute = TeknologiRouteImport.update({
  id: '/teknologi',
  path: '/teknologi',
  getParentRoute: () => rootRouteImport,
} as any)
const SejarahRoute = SejarahRouteImport.update({
  id: '/sejarah',
  path: '/sejarah',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaRoute = PetaRouteImport.update({
  id: '/peta',
  path: '/peta',
  getParentRoute: () => rootRouteImport,
} as any)
const KulinerRoute = KulinerRouteImport.update({
  id: '/kuliner',
  path: '/kuliner',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const BudayaRoute = BudayaRouteImport.update({
  id: '/budaya',
  path: '/budaya',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WisataSlugRoute = WisataSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WisataRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budaya': typeof BudayaRoute
  '/kontak': typeof KontakRoute
  '/kuliner': typeof KulinerRoute
  '/peta': typeof PetaRoute
  '/sejarah': typeof SejarahRoute
  '/teknologi': typeof TeknologiRoute
  '/wisata': typeof WisataRouteWithChildren
  '/wisata/$slug': typeof WisataSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budaya': typeof BudayaRoute
  '/kontak': typeof KontakRoute
  '/kuliner': typeof KulinerRoute
  '/peta': typeof PetaRoute
  '/sejarah': typeof SejarahRoute
  '/teknologi': typeof TeknologiRoute
  '/wisata': typeof WisataRouteWithChildren
  '/wisata/$slug': typeof WisataSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budaya': typeof BudayaRoute
  '/kontak': typeof KontakRoute
  '/kuliner': typeof KulinerRoute
  '/peta': typeof PetaRoute
  '/sejarah': typeof SejarahRoute
  '/teknologi': typeof TeknologiRoute
  '/wisata': typeof WisataRouteWithChildren
  '/wisata/$slug': typeof WisataSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budaya'
    | '/kontak'
    | '/kuliner'
    | '/peta'
    | '/sejarah'
    | '/teknologi'
    | '/wisata'
    | '/wisata/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budaya'
    | '/kontak'
    | '/kuliner'
    | '/peta'
    | '/sejarah'
    | '/teknologi'
    | '/wisata'
    | '/wisata/$slug'
  id:
    | '__root__'
    | '/'
    | '/budaya'
    | '/kontak'
    | '/kuliner'
    | '/peta'
    | '/sejarah'
    | '/teknologi'
    | '/wisata'
    | '/wisata/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudayaRoute: typeof BudayaRoute
  KontakRoute: typeof KontakRoute
  KulinerRoute: typeof KulinerRoute
  PetaRoute: typeof PetaRoute
  SejarahRoute: typeof SejarahRoute
  TeknologiRoute: typeof TeknologiRoute
  WisataRoute: typeof WisataRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wisata': {
      id: '/wisata'
      path: '/wisata'
      fullPath: '/wisata'
      preLoaderRoute: typeof WisataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teknologi': {
      id: '/teknologi'
      path: '/teknologi'
      fullPath: '/teknologi'
      preLoaderRoute: typeof TeknologiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sejarah': {
      id: '/sejarah'
      path: '/sejarah'
      fullPath: '/sejarah'
      preLoaderRoute: typeof SejarahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peta': {
      id: '/peta'
      path: '/peta'
      fullPath: '/peta'
      preLoaderRoute: typeof PetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuliner': {
      id: '/kuliner'
      path: '/kuliner'
      fullPath: '/kuliner'
      preLoaderRoute: typeof KulinerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budaya': {
      id: '/budaya'
      path: '/budaya'
      fullPath: '/budaya'
      preLoaderRoute: typeof BudayaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wisata/$slug': {
      id: '/wisata/$slug'
      path: '/$slug'
      fullPath: '/wisata/$slug'
      preLoaderRoute: typeof WisataSlugRouteImport
      parentRoute: typeof WisataRoute
    }
  }
}

interface WisataRouteChildren {
  WisataSlugRoute: typeof WisataSlugRoute
}

const WisataRouteChildren: WisataRouteChildren = {
  WisataSlugRoute: WisataSlugRoute,
}

const WisataRouteWithChildren =
  WisataRoute._addFileChildren(WisataRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudayaRoute: BudayaRoute,
  KontakRoute: KontakRoute,
  KulinerRoute: KulinerRoute,
  PetaRoute: PetaRoute,
  SejarahRoute: SejarahRoute,
  TeknologiRoute: TeknologiRoute,
  WisataRoute: WisataRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
